// Mock vehicles data - used in detail page and admin panel
export const allVehicles: Record<string, any> = {
  '2024-bmw-m4-competition': {
    id: '1',
    title: '2024 BMW M4 Competition xDrive',
    slug: '2024-bmw-m4-competition',
    make: 'BMW',
    model: 'M4',
    year: 2024,
    trim: 'Competition xDrive',
    mileage: 1200,
    mileageUnit: 'km',
    price: 98900,
    currency: 'CAD',
    fuelType: 'GASOLINE',
    transmission: 'AUTOMATIC',
    driveType: 'AWD',
    bodyType: 'COUPE',
    condition: 'NEW',
    exteriorColor: 'Brooklyn Grey',
    interiorColor: 'Black/Red',
    engine: '3.0L Twin-Turbo I6',
    horsepower: 503,
    city: 'Toronto',
    province: 'Ontario',
    description: `Experience the thrill of driving with the 2024 BMW M4 Competition xDrive. This stunning coupe combines aggressive styling with exceptional performance.`,
    featured: true,
    status: 'ACTIVE',
    views: 1234,
    reports: 0,
    features: ['Leather Seats', 'Heated Seats', 'Navigation System', 'Bluetooth', 'Backup Camera', 'Sunroof'],
    safetyFeatures: ['ABS Brakes', 'Airbags', 'Blind Spot Monitor', 'Collision Warning'],
    media: [
      { url: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200&q=80' },
      { url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=80' },
    ],
    dealer: { id: '1', businessName: 'Premium Auto Gallery', verified: true, rating: 4.8, reviewCount: 89, city: 'Toronto', province: 'Ontario' },
    user: null,
  },
  '2023-mercedes-benz-gle-450': {
    id: '2',
    title: '2023 Mercedes-Benz GLE 450',
    slug: '2023-mercedes-benz-gle-450',
    make: 'Mercedes-Benz',
    model: 'GLE',
    year: 2023,
    trim: '450 4MATIC',
    mileage: 15000,
    mileageUnit: 'km',
    price: 82500,
    originalPrice: 89900,
    currency: 'CAD',
    fuelType: 'HYBRID',
    transmission: 'AUTOMATIC',
    driveType: 'AWD',
    bodyType: 'SUV',
    condition: 'CERTIFIED_PRE_OWNED',
    exteriorColor: 'Obsidian Black',
    interiorColor: 'Macchiato Beige',
    engine: '3.0L Turbo I6 + Electric Motor',
    horsepower: 362,
    city: 'Vancouver',
    province: 'British Columbia',
    description: `The 2023 Mercedes-Benz GLE 450 combines luxury and efficiency with its mild hybrid powertrain.`,
    featured: true,
    status: 'ACTIVE',
    views: 987,
    reports: 2,
    features: ['Premium Package', 'Burmester Sound', 'Panoramic Roof', 'Air Suspension'],
    safetyFeatures: ['Pre-Safe System', 'Active Brake Assist', 'Attention Assist'],
    media: [
      { url: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=80' },
    ],
    dealer: { id: '2', businessName: 'Pacific Motors', verified: true, rating: 4.9, reviewCount: 156, city: 'Vancouver', province: 'British Columbia' },
    user: null,
  },
  '2024-tesla-model-y': {
    id: '3',
    title: '2024 Tesla Model Y',
    slug: '2024-tesla-model-y',
    make: 'Tesla',
    model: 'Model Y',
    year: 2024,
    trim: 'Long Range AWD',
    mileage: 500,
    mileageUnit: 'km',
    price: 67990,
    currency: 'CAD',
    fuelType: 'ELECTRIC',
    transmission: 'AUTOMATIC',
    driveType: 'AWD',
    bodyType: 'SUV',
    condition: 'NEW',
    exteriorColor: 'Pearl White',
    interiorColor: 'Black',
    engine: 'Dual Motor Electric',
    horsepower: 384,
    city: 'Calgary',
    province: 'Alberta',
    description: `The 2024 Tesla Model Y Long Range offers impressive range and performance.`,
    featured: false,
    status: 'ACTIVE',
    views: 2345,
    reports: 0,
    features: ['Autopilot', '15" Touchscreen', 'Glass Roof', 'Premium Audio'],
    safetyFeatures: ['Automatic Emergency Braking', 'Lane Departure Avoidance'],
    media: [
      { url: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=1200&q=80' },
    ],
    dealer: null,
    user: { id: '1', firstName: 'John', lastName: 'Smith', email: 'john@example.com' },
  },
  '2023-porsche-911-carrera': {
    id: '4',
    title: '2023 Porsche 911 Carrera S',
    slug: '2023-porsche-911-carrera',
    make: 'Porsche',
    model: '911',
    year: 2023,
    trim: 'Carrera S',
    mileage: 8500,
    mileageUnit: 'km',
    price: 159900,
    currency: 'CAD',
    fuelType: 'GASOLINE',
    transmission: 'AUTOMATIC',
    driveType: 'RWD',
    bodyType: 'COUPE',
    condition: 'USED',
    exteriorColor: 'Guards Red',
    interiorColor: 'Black Leather',
    engine: '3.0L Twin-Turbo Flat-6',
    horsepower: 443,
    city: 'Montreal',
    province: 'Quebec',
    description: `Iconic Porsche 911 Carrera S in stunning Guards Red.`,
    featured: false,
    status: 'ACTIVE',
    views: 567,
    reports: 0,
    features: ['Sport Chrono Package', 'BOSE Sound', 'Sport Exhaust'],
    safetyFeatures: ['ParkAssist', 'Lane Change Assist'],
    media: [
      { url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=80' },
    ],
    dealer: { id: '3', businessName: 'Exotic Motors Montreal', verified: true, rating: 4.9, reviewCount: 62, city: 'Montreal', province: 'Quebec' },
    user: null,
  },
  '2024-nissan-gt-r': {
    id: '5',
    title: '2024 Nissan GT-R Premium',
    slug: '2024-nissan-gt-r',
    make: 'Nissan',
    model: 'GT-R',
    year: 2024,
    trim: 'Premium',
    mileage: 2500,
    mileageUnit: 'km',
    price: 145000,
    currency: 'CAD',
    fuelType: 'GASOLINE',
    transmission: 'AUTOMATIC',
    driveType: 'AWD',
    bodyType: 'COUPE',
    condition: 'NEW',
    exteriorColor: 'Pearl White',
    interiorColor: 'Black',
    engine: '3.8L Twin-Turbo V6',
    horsepower: 565,
    city: 'Toronto',
    province: 'Ontario',
    description: `The legendary Nissan GT-R continues to deliver supercar performance.`,
    featured: true,
    status: 'ACTIVE',
    views: 1890,
    reports: 0,
    features: ['Bose Audio', 'Titanium Exhaust', 'Carbon Fiber Trim'],
    safetyFeatures: ['Vehicle Dynamic Control', 'ABS'],
    media: [
      { url: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=80' },
    ],
    dealer: { id: '4', businessName: 'Performance Auto Toronto', verified: true, rating: 4.7, reviewCount: 98, city: 'Toronto', province: 'Ontario' },
    user: null,
  },
  '2023-nissan-370z': {
    id: '6',
    title: '2023 Nissan 370Z Sport',
    slug: '2023-nissan-370z',
    make: 'Nissan',
    model: '370Z',
    year: 2023,
    trim: 'Sport',
    mileage: 12000,
    mileageUnit: 'km',
    price: 48500,
    currency: 'CAD',
    fuelType: 'GASOLINE',
    transmission: 'MANUAL',
    driveType: 'RWD',
    bodyType: 'COUPE',
    condition: 'USED',
    exteriorColor: 'Magnetic Black',
    interiorColor: 'Black Cloth',
    engine: '3.7L V6',
    horsepower: 332,
    city: 'Vancouver',
    province: 'British Columbia',
    description: `Pure driving excitement with the Nissan 370Z Sport.`,
    featured: false,
    status: 'ACTIVE',
    views: 456,
    reports: 0,
    features: ['Sport Brakes', 'Limited Slip Differential'],
    safetyFeatures: ['ABS', 'Traction Control'],
    media: [
      { url: 'https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=1200&q=80' },
    ],
    dealer: null,
    user: { id: '2', firstName: 'Jane', lastName: 'Doe', email: 'jane@example.com' },
  },
};

// Convert to array format for admin panel
export const mockListings = Object.values(allVehicles);

// Initialize mock vehicles store on import
import { initializeMockVehicles } from './mock-vehicles-store';
if (typeof window !== 'undefined') {
  // Only initialize if not already initialized from localStorage
  const stored = localStorage.getItem('mockVehicles');
  if (!stored) {
    initializeMockVehicles(allVehicles);
  }
}

